//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinFormsMeetingManager {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SampleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinFormsMeetingManager.SampleStrings", typeof(SampleStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attendee.
        /// </summary>
        public static string AddAttendeeButtonText {
            get {
                return ResourceManager.GetString("AddAttendeeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an attendee.
        /// </summary>
        public static string AddAttendeePrompt {
            get {
                return ResourceManager.GetString("AddAttendeePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        public static string AllDayMeeting {
            get {
                return ResourceManager.GetString("AllDayMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string AprilText {
            get {
                return ResourceManager.GetString("AprilText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        public static string AttendeesHeaderText {
            get {
                return ResourceManager.GetString("AttendeesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string AugustText {
            get {
                return ResourceManager.GetString("AugustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a graph client: .
        /// </summary>
        public static string ClientCreateFailed {
            get {
                return ResourceManager.GetString("ClientCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectButtonText {
            get {
                return ResourceManager.GetString("ConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButtonText {
            get {
                return ResourceManager.GetString("CreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not create the meeting. Please try again..
        /// </summary>
        public static string CreateMeetingFailed {
            get {
                return ResourceManager.GetString("CreateMeetingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not create an event: .
        /// </summary>
        public static string CreateMeetingFailedDebug {
            get {
                return ResourceManager.GetString("CreateMeetingFailedDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        public static string DailyLabelText {
            get {
                return ResourceManager.GetString("DailyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DailyText {
            get {
                return ResourceManager.GetString("DailyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateHeaderText {
            get {
                return ResourceManager.GetString("DateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date: .
        /// </summary>
        public static string DateSelectHeader {
            get {
                return ResourceManager.GetString("DateSelectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DayText {
            get {
                return ResourceManager.GetString("DayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string DecemberText {
            get {
                return ResourceManager.GetString("DecemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionHeaderText {
            get {
                return ResourceManager.GetString("DescriptionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailButtonText {
            get {
                return ResourceManager.GetString("EmailButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which type?.
        /// </summary>
        public static string EmailTypePrompt {
            get {
                return ResourceManager.GetString("EmailTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one recipient..
        /// </summary>
        public static string EmptyRecipientsListMessage {
            get {
                return ResourceManager.GetString("EmptyRecipientsListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End after.
        /// </summary>
        public static string EndAfterText {
            get {
                return ResourceManager.GetString("EndAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End by.
        /// </summary>
        public static string EndByText {
            get {
                return ResourceManager.GetString("EndByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string EndTimeHeaderText {
            get {
                return ResourceManager.GetString("EndTimeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string EveryText {
            get {
                return ResourceManager.GetString("EveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every weekday.
        /// </summary>
        public static string EveryWeekdayText {
            get {
                return ResourceManager.GetString("EveryWeekdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string FebruaryText {
            get {
                return ResourceManager.GetString("FebruaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string FirstText {
            get {
                return ResourceManager.GetString("FirstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ForwardEmailType {
            get {
                return ResourceManager.GetString("ForwardEmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        public static string FourthText {
            get {
                return ResourceManager.GetString("FourthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string FridayText {
            get {
                return ResourceManager.GetString("FridayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not get the current user&apos;s events: .
        /// </summary>
        public static string GetEventsFailed {
            get {
                return ResourceManager.GetString("GetEventsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not get users: .
        /// </summary>
        public static string GetUsersFailedDebug {
            get {
                return ResourceManager.GetString("GetUsersFailedDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string JanuaryText {
            get {
                return ResourceManager.GetString("JanuaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string JulyText {
            get {
                return ResourceManager.GetString("JulyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string JuneText {
            get {
                return ResourceManager.GetString("JuneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string LastText {
            get {
                return ResourceManager.GetString("LastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:  .
        /// </summary>
        public static string LocationHeader {
            get {
                return ResourceManager.GetString("LocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationHeaderText {
            get {
                return ResourceManager.GetString("LocationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string MarchText {
            get {
                return ResourceManager.GetString("MarchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MayText {
            get {
                return ResourceManager.GetString("MayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time     Subject.
        /// </summary>
        public static string MeetingViewHeader {
            get {
                return ResourceManager.GetString("MeetingViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string MondayText {
            get {
                return ResourceManager.GetString("MondayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        public static string MonthlyLabelText {
            get {
                return ResourceManager.GetString("MonthlyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyText {
            get {
                return ResourceManager.GetString("MonthlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end date.
        /// </summary>
        public static string NoEndDateText {
            get {
                return ResourceManager.GetString("NoEndDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string NovemberText {
            get {
                return ResourceManager.GetString("NovemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurrences.
        /// </summary>
        public static string OccurencesText {
            get {
                return ResourceManager.GetString("OccurencesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string OctoberText {
            get {
                return ResourceManager.GetString("OctoberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of every.
        /// </summary>
        public static string OfEveryText {
            get {
                return ResourceManager.GetString("OfEveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients.
        /// </summary>
        public static string RecipientsText {
            get {
                return ResourceManager.GetString("RecipientsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        public static string RecurrenceButtonText {
            get {
                return ResourceManager.GetString("RecurrenceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose recurrence type.
        /// </summary>
        public static string RecurrenceTypeChoiceText {
            get {
                return ResourceManager.GetString("RecurrenceTypeChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string RecurrenceTypeText {
            get {
                return ResourceManager.GetString("RecurrenceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshButtonText {
            get {
                return ResourceManager.GetString("RefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register your app before you run this sample..
        /// </summary>
        public static string RegisterWarning {
            get {
                return ResourceManager.GetString("RegisterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply all.
        /// </summary>
        public static string ReplyAllEmailType {
            get {
                return ResourceManager.GetString("ReplyAllEmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m running late.
        /// </summary>
        public static string RunLateButtonText {
            get {
                return ResourceManager.GetString("RunLateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m running late..
        /// </summary>
        public static string RunningLate {
            get {
                return ResourceManager.GetString("RunningLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string SaturdayText {
            get {
                return ResourceManager.GetString("SaturdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string SecondText {
            get {
                return ResourceManager.GetString("SecondText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectButtonText {
            get {
                return ResourceManager.GetString("SelectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a day.
        /// </summary>
        public static string SelectDayText {
            get {
                return ResourceManager.GetString("SelectDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not send the message. The request returned this status code: .
        /// </summary>
        public static string SendMessageFailedDebug {
            get {
                return ResourceManager.GetString("SendMessageFailedDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not send the message. Please try again..
        /// </summary>
        public static string SendMessageFailedUser {
            get {
                return ResourceManager.GetString("SendMessageFailedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string SeptemberText {
            get {
                return ResourceManager.GetString("SeptemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string SignoutButtonText {
            get {
                return ResourceManager.GetString("SignoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on.
        /// </summary>
        public static string StartOnText {
            get {
                return ResourceManager.GetString("StartOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTimeHeaderText {
            get {
                return ResourceManager.GetString("StartTimeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SubjectHeaderText {
            get {
                return ResourceManager.GetString("SubjectHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string SundayText {
            get {
                return ResourceManager.GetString("SundayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string TheText {
            get {
                return ResourceManager.GetString("TheText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        public static string ThirdText {
            get {
                return ResourceManager.GetString("ThirdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string ThursdayText {
            get {
                return ResourceManager.GetString("ThursdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string TuesdayText {
            get {
                return ResourceManager.GetString("TuesdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not update the event: .
        /// </summary>
        public static string UpdateMeetingFailedDebug {
            get {
                return ResourceManager.GetString("UpdateMeetingFailedDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string WednesdayText {
            get {
                return ResourceManager.GetString("WednesdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s) on.
        /// </summary>
        public static string WeeklyLabelText {
            get {
                return ResourceManager.GetString("WeeklyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string WeeklyText {
            get {
                return ResourceManager.GetString("WeeklyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year(s).
        /// </summary>
        public static string YearlyLabelText {
            get {
                return ResourceManager.GetString("YearlyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string YearlyText {
            get {
                return ResourceManager.GetString("YearlyText", resourceCulture);
            }
        }
    }
}
